name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "oracle"
          cache: maven

      - name: Build with Maven
        run: mvn install

      - name: Rename JAR artifacts
        run: |
          mv woodcutting/target/woodcutting-*-dep-included.jar woodcutting/target/merlins-woodcutting.jar

      - name: Upload JAR artifacts to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            woodcutting/target/merlins-woodcutting.jar
